apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-depl
spec:
# 1. Kubernetes expands horizontally, so a replica is just how many
# instances of your app that you want
# 2. Template is defining what we're deploying and the selector is 
# is selecting it
  replicas: 1
  selector:
    matchLabels:
      app: commandservice
  template:
    metadata:
      labels:
        app: commandservice
    spec:
      containers:
        - name: commandservice
          image: 47lakers/commandservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: commands-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: commandservice
  ports:
  - name: commandservice
    protocol: TCP
    port: 80
    targetPort: 80