apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
# 1. Kubernetes expands horizontally, so a replica is just how many
# instances of your app that you want
# 2. Template is defining what we're deploying and the selector is 
# is selecting it
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: 47lakers/platformservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector: 
    app: platformservice
  ports:
  - name: platformservice
    protocol: TCP
    port: 80
    targetPort: 80